package com.inspiredandroid.kai.ui.settings
import androidx.compose.runtime.Immutable
import com.inspiredandroid.kai.data.ImportSection
import com.inspiredandroid.kai.data.Service
import com.inspiredandroid.kai.data.ThemeMode
import com.inspiredandroid.kai.inference.LocalModel
import com.inspiredandroid.kai.mcp.PopularMcpServer
import io.github.vinceglb.filekit.PlatformFile

            onAddMcpServer = { _, _, _ -> },
            onAddPopularMcpServer = {},
            onAddService = {},
            onCancelLocalModelDownload = {},
            onCancelLocalModelImport = {},
            onCancelTask = {},
            onChangeApiKey = { _, _ -> },
            onChangeBaseUrl = { _, _ -> },
            onChangeCustomModelId = { _, _ -> },
            onChangeEmailPollInterval = {},
            onChangeHeartbeatActiveHours = { _, _ -> },
            onChangeHeartbeatInterval = {},
            onChangeHeartbeatService = {},
            onChangeModelContextTokens = { _, _ -> },
            onChangeSmsPollInterval = {},
            onChangeThemeMode = {},
            onChangeUiScale = {},
            onClearPendingNotifications = {},
            onDeleteLocalModel = {},
            onDeleteMemory = {},
            onDownloadLocalModel = {},
            onExpandService = {},
            onExportSettings = { _ -> "" },
            onImportLocalModel = {},
            onImportSettings = { _, _, _ -> ImportResult.Failure },
            onInstallBrowsedSkill = {},
            onInstallGitHubSkill = {},
            onOpenAppPermissionSettings = {},
            onOpenNotificationListenerSettings = {},
            onPrepareExport = { emptyMap() },
            onRecheckLocalNetworkPermission = {},
            onRefreshEmailAccount = {},
            onRefreshHeartbeat = {},
            onRefreshMcpServer = {},
            onRefreshSms = {},
            onRemoveEmailAccount = {},
            onRemoveMcpServer = {},
            onRemoveService = {},
            onReorderServices = {},
            onSaveHeartbeatPrompt = {},
            onSaveSoul = {},
            onSelectModel = { _, _ -> },
            onSelectTab = {},
            onShowAddMcpServerDialog = {},
            onShowAddSkillDialog = {},
            onToggleDaemon = {},
            onToggleDynamicUi = {},
            onToggleEmail = {},
            onToggleFreeFallback = {},
            onToggleHeartbeat = {},
            onToggleMcpServer = { _, _ -> },
            onToggleMemory = {},
            onToggleNotifications = {},
            onToggleScheduling = {},
            onToggleSms = {},
            onToggleSmsSend = {},
            onToggleTool = { _, _ -> },
            onToggleUseCustomModel = { _, _ -> },
            onUndoDelete = {},
            onUninstallSkill = {},
            onUpdateMemory = { _, _ -> },
        )
        val NoOp = SettingsActions(
    companion object {
    val onAddMcpServer: (String, String, Map<String, String>) -> Unit,
    val onAddPopularMcpServer: (PopularMcpServer) -> Unit,
    val onAddService: (Service) -> Unit,
    val onCancelLocalModelDownload: () -> Unit,
    val onCancelLocalModelImport: () -> Unit,
    val onCancelTask: (String) -> Unit,
    val onChangeApiKey: (String, String) -> Unit,
    val onChangeBaseUrl: (String, String) -> Unit,
    val onChangeCustomModelId: (String, String) -> Unit,
    val onChangeEmailPollInterval: (Int) -> Unit,
    val onChangeHeartbeatActiveHours: (Int, Int) -> Unit,
    val onChangeHeartbeatInterval: (Int) -> Unit,
    val onChangeHeartbeatService: (String?) -> Unit,
    val onChangeModelContextTokens: (String, Int) -> Unit,
    val onChangeSmsPollInterval: (Int) -> Unit,
    val onChangeThemeMode: (ThemeMode) -> Unit,
    val onChangeUiScale: (Float) -> Unit,
    val onClearPendingNotifications: () -> Unit,
    val onDeleteLocalModel: (String) -> Unit,
    val onDeleteMemory: (String) -> Unit,
    val onDownloadLocalModel: (LocalModel) -> Unit,
    val onExpandService: (String?) -> Unit,
    val onExportSettings: (Set<ImportSection>) -> String,
    val onImportLocalModel: (PlatformFile) -> Unit,
    val onImportSettings: (ByteArray, Set<ImportSection>, Boolean) -> ImportResult,
    val onInstallBrowsedSkill: (com.inspiredandroid.kai.skills.RegistrySkillEntry) -> Unit,
    val onInstallGitHubSkill: (String) -> Unit,
    val onOpenAppPermissionSettings: () -> Unit,
    val onOpenNotificationListenerSettings: () -> Unit,
    val onPrepareExport: () -> Map<ImportSection, String?>,
    val onRecheckLocalNetworkPermission: (String) -> Unit,
    val onRefreshEmailAccount: (String) -> Unit,
    val onRefreshHeartbeat: () -> Unit,
    val onRefreshMcpServer: (String) -> Unit,
    val onRefreshSms: () -> Unit,
    val onRemoveEmailAccount: (String) -> Unit,
    val onRemoveMcpServer: (String) -> Unit,
    val onRemoveService: (String) -> Unit,
    val onReorderServices: (List<String>) -> Unit,
    val onSaveHeartbeatPrompt: (String) -> Unit,
    val onSaveSoul: (String) -> Unit,
    val onSelectModel: (String, String) -> Unit,
    val onSelectTab: (SettingsTab) -> Unit,
    val onShowAddMcpServerDialog: (Boolean) -> Unit,
    val onShowAddSkillDialog: (Boolean) -> Unit,
    val onToggleDaemon: (Boolean) -> Unit,
    val onToggleDynamicUi: (Boolean) -> Unit,
    val onToggleEmail: (Boolean) -> Unit,
    val onToggleFreeFallback: (Boolean) -> Unit,
    val onToggleHeartbeat: (Boolean) -> Unit,
    val onToggleMcpServer: (String, Boolean) -> Unit,
    val onToggleMemory: (Boolean) -> Unit,
    val onToggleNotifications: (Boolean) -> Unit,
    val onToggleScheduling: (Boolean) -> Unit,
    val onToggleSms: (Boolean) -> Unit,
    val onToggleSmsSend: (Boolean) -> Unit,
    val onToggleTool: (String, Boolean) -> Unit,
    val onToggleUseCustomModel: (String, Boolean) -> Unit,
    val onUndoDelete: () -> Unit,
    val onUninstallSkill: (String) -> Unit,
    val onUpdateMemory: (String, String) -> Unit,
    }
) {
@Immutable
data class SettingsActions(
}
